
TOPICS = [
    "Beach",
    "Mountains",
    "Sunset",
    "Forest",
    "City Lights",
    "Abstract Art",
    "Cats",
    "Dogs",
    "Space Exploration",
    "Galaxies",
    "Auroras",
    "Waterfalls",
    "Architecture",
    "Vintage Cars",
    "Bicycles",
    "Minimalist Patterns",
    "Typography",
    "Rainbows",
    "Underwater",
    "National Parks",
    "Winter Scenery",
    "Desert Landscapes",
    "Abstract Geometric",
    "Coffee",
    "Tea",
    "Sweets and Desserts",
    "Books and Libraries",
    "Travel Destinations",
    "Outer Space",
    "Botanical Gardens",
    "Rainy Days",
    "Starry Nights",
    "Technology",
    "Graffiti",
    "Neon Lights",
    "Artistic Paintings",
    "Wildlife",
    "Superheroes",
    "Fantasy Creatures",
    "Dreamy Landscapes",
    "Sci-Fi",
    "Futuristic Cities",
    "Water Reflections",
    "Retro Gaming",
    "Fantasy Landscapes",
    "Zen Gardens",
    "Vintage Cameras",
    "Colorful Patterns",
    "Dark Mode",
    "Summer Vibes",
    "Autumn Leaves",
    "Spring Flowers",
    "Meditation",
    "Unicorn",
    "Rainy Windows",
    "Rustic Countryside",
    "Bokeh",
    "Glowing Neon",
    "Art Deco",
    "Foggy Landscapes",
    "Hot Air Balloons",
    "Inspirational Quotes",  
    "Beach Sunset",
    "Snowy Mountains",
    "Autumn Forest",
    "City Skylines",
    "Abstract Patterns",
    "Cute Kittens",
    "Playful Puppies",
    "Astronomy",
    "Nebulas",
    "Lakes and Rivers",
    "Modern Architecture",
    "Classic Cars",
    "Vintage Bicycles",
    "Artistic Portraits",
    "Minimalist Landscapes",
    "Calligraphy",
    "Watercolor Paintings",
    "Stormy Weather",
    "Coral Reefs",
    "Famous Landmarks",
    "Christmas",
    "Halloween",
    "Fireworks",
    "Coffee Art",
    "Tea Time",
    "Delicious Food",
    "Abstract Books",
    "Adventure Travel",
    "Deep Space",
    "Tropical Flowers",
    "Enchanted Forests",
    "Fairy Tales",
    "Cyberpunk",
    "Robots",
    "Dragons",
    "Dream Catchers",
    "Outer Space Colonies",
    "Waterfalls at Night",
    "Pixel Art",
    "Arcade Games",
    "Steampunk",
    "Surreal Landscapes",
    "Japanese Gardens",
    "Retro Patterns",
    "Glowing Neon Signs",
    "Vintage Posters",
    "Foggy Mountains",
    "Hot Air Balloon Festivals",
    "Summer Beach Vibes",
    "Vibrant Fall Foliage",
    "Cherry Blossoms",
    "Yoga and Meditation",
    "Magical Creatures",
    "Rainy Cityscapes",
    "Country Farm Life",
    "Bokeh Lights",
    "Cosmic Horizons",
    "Tropical Islands",
    "Art Nouveau",
    "Misty Valleys",
    "Kites in the Sky",
    "Colorful Abstracts",
    "Time Travel",
    "Galactic Battles",
    "Colorful Glitch Art",
    "Futuristic Skyscrapers",
]
